language: python
python: 3.4
sudo: required

branches:
    only:
        - test-spider
        - /^\d\.\d+$/

services:
    - docker

before_install:
    - docker run -d -p 8050:8050 scrapinghub/splash

install:
    - pip install -U tox codecov

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip
