language: python
python: 3.5
sudo: required

branches:
    only:
        - master
        - /^\d\.\d+$/

services:
    - docker

before_install:
    - docker run -d -p 8050:8050 scrapinghub/splash

addons:
    apt:
        packages:
            - python-numpy
            - python-scipy
            - libatlas-base-dev
            - liblapack-dev
            - gfortran

install:
    - pip install -U tox codecov

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip
